# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_avalongame_avalongameuser_avalonquest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avalongame',
            old_name='creator',
            new_name='user',
        ),
    ]
