# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_avalongame_avalongameuser_avalonquest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvalonGame',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='AvalonGameUser',
            new_name='GameUser',
        ),
        migrations.RenameModel(
            old_name='AvalonQuest',
            new_name='Quest',
        ),
    ]
